CREATE DATABASE DB_FilmBooking;
GO

USE [DB_FilmBooking];
GO
CREATE TABLE Person
(
  ID int NOT NULL IDENTITY(1,1),
  FirstName NVARCHAR(20),
  LastName NVARCHAR(20),
  CONSTRAINT pk_PersonID PRIMARY KEY (ID) 
)
GO

CREATE TABLE Director
(
  ID INT NOT NULL IDENTITY(100,1),
  PersonID INT,
  CONSTRAINT pk_directorID PRIMARY KEY(ID),
  CONSTRAINT fk_personID FOREIGN KEY (PersonID) REFERENCES Person(ID)
)
GO

CREATE TABLE [User]
(
	ID INT NOT NULL IDENTITY(600,1),
	PersonID INT NOT NULL,
	Balance FLOAT NOT NULL,
	[Login] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(300) NOT NULL,
	CONSTRAINT pk_USerID PRIMARY KEY(ID),
	CONSTRAINT fk_uPersonID FOREIGN KEY (PersonID) REFERENCES Person(ID),
	CONSTRAINT UQ_User_Login UNIQUE ([Login])
)
GO

CREATE TABLE Film
(
  ID int NOT NULL IDENTITY(800,1),
  Title NVARCHAR(70),
  Genre NVARCHAR(20),
  YearRelease INT NOT NULL,
  DirectorID INT NOT NULL,
  Price FLOAT NOT NULL,
  IMDb FLOAT,
  CONSTRAINT pk_filmID PRIMARY KEY(ID),
  CONSTRAINT fk_directorID FOREIGN KEY (DirectorID) REFERENCES Director(ID)
)
GO

CREATE TABLE [Order]
(
	ID INT NOT NULL IDENTITY(1000,1),
	UserID INT NOT NULL,
	FilmID INT NOT NULL,
	OrderDate DATETIME,
	CONSTRAINT pk_OrderID PRIMARY KEY(ID),
    CONSTRAINT fk_UserID FOREIGN KEY (UserID) REFERENCES [User](ID),
	CONSTRAINT fk_FilmID FOREIGN KEY(FilmID) REFERENCES Film(ID)
)
GO




